# Generated by Django 4.1 on 2022-10-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='tel',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
